rotation:
    logLimit: 5242880 # 5MB
    keepFiles: 20
severity: Debug
file: importer-db-consistency-node.log
node:
    plugin:
        notifier:
            severity: Debug
            file: importer-db-consistency.log
            socket-io:
                severity: Debug
                file: socket-io.log
drop:
    severity: Error

